### PR TITLE
[minor] update: invalid client name warning handling

### PR DESCRIPTION
**Pull request by varshini-senthil**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-labview/blob/main/CONTRIBUTING.md). _(Required)_
- [ ]  Automatically post PR comments with images for G code changes? _(Recommended for small changes)_

### What does this Pull Request accomplish?

- Updated the workflow of handling the warning for invalid client names.
    - Currently, we highlight all the invalid client names among the populated list of available measurements when the user edits or selects a measurement service.
    - In this PR, the workflow is updated to highlight the invalid client names of the measurement services that are selected for client creation.
- Removed the `Validate Client Names.vi`, due to change in workflow and also updated the automated test case to use the `Validate Selected Client Names.vi` instead of the `Validate Client Names.vi`.
    - Updated the scope of `Validate Selected Client Names.vi` to 'community' scope, to use the VI in the automated test case.

### Why should this Pull Request be merged?

- To update the workflow of handling the warning for invalid client names.
- To update the automated test case, which checks for duplicate client names in the multicolumn listbox.

### What testing has been done?

- Manually tested the highlighting of invalid client names and visibility of warning for various test cases.

### CODE REVIEW

**Comment by varshini-senthil** [comment]
`Update Measurement Selection.vi`
- Remove the highlight of the invalid client's name, if the measurement is unchecked (not selected).

Diff image
Before:
image

After:
image

**Comment by varshini-senthil** [comment]
`Create Measurement Client.vi`
Diff image

**Mouse down case**
Before:
image
After:
image

**Comment by varshini-senthil** [comment]
`Create Measurement Client.vi`
Diff image

**Edit cell case**
Before:
image
After:
image

**Comment by varshini-senthil** [comment]
`test_DuplicateClientNames_CheckClientNameIsNotRepeated_NameInvalid.vi`
- Updated the automated test case to check for invalid client names only for the selected measurements in the multicolumn listbox.

Diff image
Before:
image

After:
image

**Review by dixonjoel — APPROVED** [review]

**Pull request merged**
